program stitching
!
!
!
!OPTION 1: READING IN FIXED FILES. 
!DICTATE THE FRAGMENTS THAT YOU WANTED STITCHED TOGETHER USING THE ABSOLUTE PATH OF THEIR RXP FILES.
!TO ALLOW AN ARBITRARY STRUCTURE TO BE STITCHED TOGETHER, WE'LL READ IN THE LIST OF THE FRAGMENTS' 
!ABSOLUTE PATHS IN THE ORDER THAT THEY ARE TO BE STITCHED IN. THE PATHS SHOULD BE PROVIDED 
!IN A FILE CALLED 'fragments.in'
implicit none::
character(len=180)::rxpline,fragpath
real*8::
integer::io
open(unit=10, file='fragments.in')
100 format(A180)
read(10,100,iostat=io)fragpath

