program readtest
!
!
implicit none
character(len=30)::file1 ,word(8)
!real*8::coord(3,3,24)=0,rc1(3)=0,rn1(3)=0,rn2(3)=0,rc2(3)=0
!real*8::getbond,getbang,getbtor
integer::io !n=0,l=0,m=0,j=0,k=0,hit(24,24)=0,io
open(unit=11, file='/home/ethan/codetest/word/filename')
open(unit=12, file='test_in')
!open(unit=13, file='test_coord')
!open(unit=14, file='dist')
!open(unit=15, file='bang1')
!open(unit=16, file='bang2')
!open(unit=17, file='bangtor')
!open(unit=18, file='hist')
100 format(A30)
101 format(F7.3,F7.3,F7.3)
!
!
!read(11,100) file1 !read in file name from generated by cncgen.sh
!write(12,100)file1 !TEST: write out the filenames read in from cncgen.sh. Comment out
!
!Loop over the all of the different files to read in their coordinates starts here.
!comment out the loop to read in a single file for testing purposes.
!
!
do  !index of entries in file1; gives the file name
read(11,100,iostat=io)file1
 if (io < 0 ) then
  exit
! else if (io > 0) then
 ! write(*,*) 'FUBAR'
 else if (io == 0) then
 open(unit=21, file= file1)
 read(21,*) word
 write(12,100)file1
 write(12,*) word(4)
 end if
end do 
!
!the line below writes out the collection of coordinates for double checking
!commentout as needed.
!write(13,101) coord(1,1,2),coord(2,1,2),coord(3,1,2)
!!do m=1,23 !loop over the coordinates of the 24 residue in the polyuracil pairwise
! j=m+1 
! do l=j,24 !
!  rn1(1)=coord(1,2,m)
!  rn1(2)=coord(2,2,m)
!  rn1(3)=coord(3,2,m)
!  rn2(1)=coord(1,2,l)
!  rn2(2)=coord(2,2,l)
!  rn2(3)=coord(3,2,l)
!!write(*,*) rn1  
!  !write(4,*) getbond(rn1,rn2)
!  if (getbond(rn1,rn2)<=9.5 .and. getbond(rn1,rn2)>=8.5) then
!   !write(*,*) 'nucleotides',m,'and',l,'are sufficiently close'
!!   rc1(1)=coord(1,1,m)
!!   rc1(2)=coord(2,1,m)
!   rc1(3)=coord(3,1,m)
!   rc2(1)=coord(1,1,l)
!   rc2(2)=coord(2,1,l)
!   rc2(3)=coord(3,1,l)
!   write(15,*) getbang(rc1,rn1,rn2)
!   if (getbang(rc1,rn1,rn2)<=2.5307274154 .and. getbang(rc1,rn1,rn2)>=1.8325957146) then
!    write(16,*) getbang(rn1,rn2,rc2)
!    if (getbang(rn1,rn2,rc2)<=2.5307274154 .and. getbang(rn1,rn2,rc2)>=1.8325957146) then
 !   ! write(*,*) 'nucleotides',m,'and',l,'are sufficiently unstrained'
 !    write(17,*)getbtor(rc1,rn1,rn2,rc2)
 !    if (abs(getbtor(rc1,rn1,rn2,rc2))<=0.6981317008) then
      !write(*,*) 'nucleotide', m, 'and', l, 'base-paired'
!      hit(m,l)=hit(m,l)+1
!      write(*,*)m,'and',l,'base paired'
!     endif 
!    endif
!   endif
!  endif
   !if !check if the two residue are close enough together
   !then !place holder for result of GETBANG.F
     !if i! check if the two residue forms the correct cnc bond angle
      !then !place holder for result of torsion angle
       !if !check the tosion angles is sufficiently small
        !then hit(l,m,n)=1 !final check for torsion angle
       !else hit(l,m,n)=0
     !else hit(l,m,n)=0 !exit condition for bond angle
   !else hit(l,m,n)=0 !exit condition for bond length
  !end if !end of if loop for a given m,n pair
!!end do!end the loop over l, thie second residue of the pairing
!end do! end loop over m, the first residue of the pairing
!end do ! end loop over n, the index of the pdb output.
!end do
!103 format(24(i5))
!!write(8,103)hit
!write(18,103) hit
stop 
end
